import VerticalBox from "./UI/VerticalBox";
import Province from "./Province";
import DivisionTemplate from "./DivisionTemplate";
import Combat from "./Combat";
import Jsonable from "./Jsonable";
export default class Division extends VerticalBox implements Jsonable {
    private static __selects;
    private __selected;
    private __onMap;
    private __template;
    private __province;
    private _organization;
    private __destination;
    private movingProgress;
    private __progressBar;
    private __combats;
    private __dead;
    constructor(template: DivisionTemplate);
    setOnMap(flag: boolean): void;
    getOnMap(): boolean;
    select(): void;
    deselect(): void;
    private onClick;
    static moveSelectingDivisionsTo(province: Province): void;
    set at(provinceId: string);
    set destination(provinceId: string);
    setPosition(province: Province): void;
    getPosition(): Province;
    get owner(): import("./Country").default;
    get sprite(): this;
    attack(target: Division): void;
    getOrganization(): number;
    setOrganization(organization: number): void;
    getTemplate(): DivisionTemplate;
    move(destination: Province): void;
    private hasCombatWith;
    addCombat(combat: Combat): void;
    removeCombat(combat: Combat): void;
    destroy(): void;
    stopMove(): void;
    update(): void;
    toJSON(): any;
}
