import VerticalBox from "./UI/VerticalBox";
import Province from "./Province";
import DivisionTemplate from "./DivisionTemplate";
import Combat from "./Combat";
import Jsonable from "./Jsonable";
export default class Division extends VerticalBox implements Jsonable {
    private static selects;
    private selected;
    private onMap;
    private template;
    private $province;
    private $organization;
    private $destination;
    private $movingProgress;
    private progressBar;
    private combats;
    private dead;
    constructor(template: DivisionTemplate);
    onResourceLoaded(): void;
    private set organization(value);
    private set movingProgress(value);
    setOnMap(flag: boolean): void;
    getOnMap(): any;
    select(): void;
    deselect(): void;
    private onClick;
    static moveSelectingDivisionsTo(province: Province): void;
    set province(provinceId: string);
    set destination(provinceId: string);
    setPosition(province: Province): void;
    getPosition(): Province;
    get owner(): import("./Country").default;
    get sprite(): this;
    attack(target: Division): void;
    getOrganization(): number;
    setOrganization(organization: number): void;
    getTemplate(): DivisionTemplate;
    move(destination: Province): void;
    private hasCombatWith;
    addCombat(combat: Combat): void;
    removeCombat(combat: Combat): void;
    destroy(): void;
    stopMove(): void;
    update(): void;
    toJSON(): any;
}
