import Country from "./Country";
import Province from "./Province";
import DivisionTemplate from "./DivisionTemplate";
import Combat from "./Combat";
import DivisionSprite from "./DivisionSprite";
export default class DivisionInfo {
    private __template;
    private _position;
    private _organization;
    private __sprite;
    private _destination;
    private movingProgress;
    private __progressBar;
    private __combats;
    private __dead;
    constructor(template: DivisionTemplate);
    createSprite(): void;
    set position(provinceId: string);
    set destination(provinceId: string);
    setPosition(province: Province): void;
    getPosition(): Province;
    get owner(): Country;
    get sprite(): DivisionSprite;
    attack(target: DivisionInfo): void;
    getOrganization(): number;
    setOrganization(organization: number): void;
    getTemplate(): DivisionTemplate;
    moveTo(destination: Province): void;
    private hasCombatWith;
    addCombat(combat: Combat): void;
    removeCombat(combat: Combat): void;
    destroy(): void;
    stopMove(): void;
    update(): void;
    private toJSON;
}
