import { Scene } from "./Scene";
import { Country } from "../Country";
import { LoaderAddParam } from "../Utils/LoaderAddParam";
import { Atlas } from "../Map/Atlas";
import { Selectable } from "./Selectable";
import { Province } from "../Province";
import { DivisionSprite } from "../DivisionSprite";
import { Observable } from "Observable";
import { PlayCountryObserver } from "../PlayCountryObserver";
export class MainScene extends Scene implements Selectable, Observable {
  static instance: MainScene;
  private playCountry;
  private map;
  private header;
  private sidebar;
  selectingDivison: DivisionSprite;
  cheat_move: boolean;
  private observers;
  constructor(playCountry: Country);
  protected createInitialResourceList(): (LoaderAddParam | string)[];
  protected onResourceLoaded(): void;
  selectProvince(province: Province): void;
  openDiplomacySidebar(country: Country): void;
  openConscription(): void;
  openDebug(): void;
  openProvinceSidebar(province: Province): void;
  getMap(): Atlas;
  update(dt: number): void;
  getMyCountry(): Country;
  setPlayCountry(country: Country): void;
  getDate(): Date;
  addObserver(observer: PlayCountryObserver): void;
  removeObserver(observer: PlayCountryObserver): void;
}
